server:
  port: 8081

spring:
  application:
    name: edusphere
  profiles:
    active: local
  datasource:

    url: jdbc:mysql://localhost:3306/edusphere?useSSL=false&serverTimezone=UTC

    username: Pon

    password: Madhu@12

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:

    hibernate:

      ddl-auto: update

    show-sql: true





jwt:

  secret: qKGhdukK2Op8FP+U6DWc7/hI11SfSo9s+IKnqlDAZqKyBcQ35pXwkbO/pncYk20F9EeR8bHn6unP1yM+f1Xbfg==

