package com.cts.edusphere.services.audit_log;

import com.cts.edusphere.common.dto.audit_log.AuditLogResponseDTO;
import com.cts.edusphere.enums.Severity;
import com.cts.edusphere.enums.SystemLogType;

import java.util.List;
import java.util.UUID;

/**
 * Service interface defining the contract for system audit log management within EduSphere.
 *
 * <p>Provides methods for recording system-level events and querying the audit log by
 * various criteria including user, resource, severity, and event type. Audit logs serve
 * as an immutable trail of significant system actions for security monitoring, debugging,
 * and compliance reporting.</p>
 */
public interface AuditLogService {

    /**
     * Records a new system event in the audit log.
     *
     * <p>This method is intended for internal use by services and AOP aspects to capture
     * meaningful system events without requiring a full DTO round-trip.</p>
     *
     * @param logType  the {@link SystemLogType} categorising the nature of the event
     *                 (e.g., AUTHENTICATION, DATA_ACCESS, CONFIGURATION_CHANGE)
     * @param severity the {@link Severity} level indicating the importance of the event
     *                 (e.g., INFO, WARNING, ERROR, CRITICAL)
     * @param action   a short, human-readable description of the action performed (e.g., "USER_LOGIN")
     * @param resource the name or identifier of the resource affected by the action (e.g., "User", "/api/users")
     * @param details  additional contextual information about the event; may be {@code null}
     * @param userId   the {@link UUID} of the user who triggered the event;
     *                 may be {@code null} for system-initiated events
     */
    void logSystemEvent(SystemLogType logType, Severity severity, String action, String resource, String details, UUID userId);

    /**
     * Retrieves all audit log entries in the system.
     *
     * @return a {@link List} of {@link AuditLogResponseDTO} objects representing all log entries;
     *         never {@code null}, may be empty
     */
    List<AuditLogResponseDTO> getAllLogs();

    /**
     * Retrieves a single audit log entry by its unique identifier.
     *
     * @param id the {@link UUID} of the log entry to retrieve
     * @return an {@link AuditLogResponseDTO} representing the found log entry
     * @throws com.cts.edusphere.exceptions.ResourceNotFoundException if no log entry exists with the given ID
     */
    AuditLogResponseDTO getLogById(UUID id);

    /**
     * Retrieves all audit log entries generated by or attributed to a specific user.
     *
     * @param userId the {@link UUID} of the user whose log entries are to be retrieved
     * @return a {@link List} of {@link AuditLogResponseDTO} objects for the given user;
     *         never {@code null}, may be empty if the user has no log entries
     */
    List<AuditLogResponseDTO> getLogsByUser(UUID userId);

    /**
     * Retrieves all audit log entries related to a specific resource.
     *
     * @param resource the resource name or path to filter by (e.g., "User", "/api/courses")
     * @return a {@link List} of {@link AuditLogResponseDTO} objects for the given resource;
     *         never {@code null}, may be empty if no logs reference that resource
     */
    List<AuditLogResponseDTO> getLogsByResource(String resource);

    /**
     * Retrieves all audit log entries with a specific severity level.
     *
     * @param severity the {@link Severity} to filter by (e.g., INFO, WARNING, ERROR, CRITICAL)
     * @return a {@link List} of {@link AuditLogResponseDTO} objects matching the given severity;
     *         never {@code null}, may be empty
     */
    List<AuditLogResponseDTO> getLogsBySeverity(Severity severity);

    /**
     * Retrieves all audit log entries of a specific system log type.
     *
     * @param logType the {@link SystemLogType} to filter by
     *                (e.g., AUTHENTICATION, DATA_ACCESS, CONFIGURATION_CHANGE)
     * @return a {@link List} of {@link AuditLogResponseDTO} objects matching the given log type;
     *         never {@code null}, may be empty
     */
    List<AuditLogResponseDTO> getLogsByType(SystemLogType logType);
}
