package com.cts.edusphere.enums;

public enum AuditEntityType {
    STUDENT_CREATED,
    STUDENT_UPDATED,
    STUDENT_DELETED,

    DEPARTMENT_CREATED,
    DEPARTMENT_UPDATED,
    DEPARTMENT_DELETED,

    FACULTY_CREATED,
    FACULTY_UPDATED,
    FACULTY_DELETED,

    COURSE_CREATED,
    COURSE_UPDATED,
    COURSE_DELETED,

    USER_REGISTERED,
    USER_DEACTIVATED,
    USER_ROLE_CHANGED,

    DOCUMENT_UPLOADED,
    DOCUMENT_VERIFIED,
    DOCUMENT_REJECTED,

    EXAM_CREATED,
    GRADE_ASSIGNED,

    OTHER
}
