package com.cts.edusphere.enums;

public enum ReportScope {
    STUDENT_PERFORMANCE,
    FACULTY_WORKLOAD,
    DEPARTMENT_OVERVIEW,
    COURSE_ANALYTICS,
    EXAM_RESULTS,
    THESIS_STATUS,
    RESEARCH_PROGRESS,
    COMPLIANCE_SUMMARY,
    AUDIT_SUMMARY
}
